apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  local:
    path: /NAS-volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values:
            - disk1  