apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml

secretGenerator:
  - name: pihole-pass
    files:
    - pihole-pass