apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - samba

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: nginx
  namespace: default
  valuesFile: values.yaml