apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: smbcredentials
    files:
    - smbuser
    - smbpass