apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samba

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml

secretGenerator:
  - name: smbcredentials
    files:
    - smbuser
    - smbpass