apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/philgladman/home-rpi-NAS.git
    targetRevision: argocd
    path: kustomize/apps
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
