apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: samba
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
      - image: philgman1121/samba
        name: samba
        env:
          - name: USER
            valueFrom:
              secretKeyRef:
                name: smbcredentials
                key: smbuser
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: smbcredentials
                key: smbpass
        ports: 
          - containerPort: 139
            name: smb-139
          - containerPort: 445
            name: smb-445
        volumeMounts:
          - name: samba-persistent-storage
            mountPath: /NAS-volume
      volumes:
        - name: samba-persistent-storage
          persistentVolumeClaim:
            claimName: my-claim
      nodeSelector:
        disk: disk1